fun main() {
    val persona = Persona("Ivan",21)
    val empleado1 = Empleado("Ivan",21,12000.0,11.0)
    val empleado2 = Empleado("Cesar",20,800,21)
    val gerente1 = Gerente("Ivan",21,6000,20,1200,false)
    val gerente2 = Gerente("Ivan",21,6000,20,1200,true)

    println("PERSONA\n${persona}")
    println(persona.celebrarCumple())
    println()
    println("EMPLEADO 1\n${empleado1}")
    println(empleado1.trabajar())
    println()
    println("EMPLEADO 2\n${empleado2}")
    println(empleado2.celebrarCumple())
    println(empleado2.trabajar())
    println()
    println("GERENTE SIN EXENTO\n${gerente1}")
    println(gerente1.administrar())
    println()
    println("GERENTE CON EXENTO\n${gerente2}")
    println(gerente2.trabajar())
    println(gerente2.administrar())
}